chat:
  enabled: true
  pattern: "&b%NAME% &7❯ &f"
  emojis:
    enabled: true
    symbol: ":"
  transliteration:
    enabled: true
    button-pattern: "&8&l♺"
    button-hover: "Транслитерировать"
    pattern: "&8(транслитерировано)"
    already-transliterated:
      title: ""
      subtitle: "&cСообщение уже транслитерировано"
      time: 3
  chat-history:
    enabled: true
    message: "&bИстория чата загружена!"
  links:
    enabled: true
    https:
      pattern: "&aссылка"
      hover: "Ведёт на: %LINK%"
    http:
      pattern: "&cне защищённая ссылка"
      hover: "Ведёт на: %LINK%"
  mentions:
    enabled: true
    symbol: "@"
    answer-hover: "Нажмите чтобы ответить"
    pattern: "&e@%MENTION%"
    hover: "Игрок %AUTHOR% упомянул игрока %MENTION%"
    everyone:
      enabled: true
      pattern: "&6@everyone"
      hover: "Игрок %AUTHOR% упомянул всех игроков"
    title:
      title: ""
      subtitle: "&e%AUTHOR% упомянул вас"
      time: 3