chat:
  enabled: true
  pattern: "&b%NAME% &7❯ &f"
  answers:
    enabled: true
    hover: "Нажмите чтобы ответить"
    pattern: "&b┌ &7Ответ на: %MESSAGE%"
    title:
      title: ""
      subtitle: "&b%AUTHOR% ответил(а) вам"
      time: 3
  emojis:
    enabled: true
    symbol: ":"
  transliteration:
    enabled: true
    button-pattern: "&8&l♺"
    button-hover: "Транслитерировать"
    pattern: "&8(транслитерировано)"
    already-transliterated:
      title: ""
      subtitle: "&cСообщение уже транслитерировано"
      time: 3
  chat-history:
    enabled: true
    message: "&bИстория чата загружена!"
  links:
    enabled: true
    https:
      pattern: "&aссылка"
      hover: "Ведёт на: %LINK%"
    http:
      pattern: "&cне защищённая ссылка"
      hover: "Ведёт на: %LINK%"
  mentions:
    enabled: true
    symbol: "@"
    mention-hover: "Нажмите чтобы упомянуть"
    pattern: "&e@%MENTION%"
    everyone:
      enabled: true
      pattern: "&6@everyone"
    title:
      title: ""
      subtitle: "&e%AUTHOR% упомянул(а) вас"
      time: 3